
data_config:
  data_path: "..\\dataset\\data"

diffusion_config:
  beta_start: 0.0001
  beta_end: 0.02
  num_timesteps: 1000

model_config:
  img_channels: 1
  img_size: 28
  time_emb_dim: 128

  down_channels: [32, 64, 128, 256]
  mid_channels: [256, 256, 128]
# up_channels: block1:[128*2, 64], block2:[64*2, 32], block3:[32*2, 16]

  down_layers: 2
  mid_layers: 2
  up_layers: 2

  num_heads: 4

  down_sample: [True, True, False]

train_config:
  task_name: "ddpm_train"
  ckpt_name: "ddpm_ckpt.pth"
  num_samples: 100
  lr: 0.0001
  num_epochs: 64
  batch_size: 64
  log_name: 'training.log'